# Generated by Django 4.2.7 on 2025-04-18 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club_slug', models.CharField(max_length=30)),
                ('contest_slug', models.CharField(max_length=30)),
                ('is_solo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamContestRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(db_column='contest', on_delete=django.db.models.deletion.CASCADE, related_name='registered_teams', to='contests.contest')),
                ('team', models.ForeignKey(db_column='team', on_delete=django.db.models.deletion.CASCADE, related_name='registered_team_contests', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamContestUserRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_contest_registration', models.ForeignKey(db_column='team_contest_registration', on_delete=django.db.models.deletion.CASCADE, related_name='registered_members', to='contests.teamcontestregistration')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='team_contest_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoloContestRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(db_column='contest', on_delete=django.db.models.deletion.CASCADE, related_name='registered_users', to='contests.contest')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='registered_solo_contests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
